# Generated by Django 6.0.4 on 2026-04-28 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protocol', models.CharField(max_length=20, unique=True, verbose_name='protocolo')),
                ('status', models.CharField(choices=[('received', 'Recebido'), ('preparing', 'Em preparo'), ('ready', 'Pronto'), ('delivered', 'Entregue')], default='received', max_length=20, verbose_name='status')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Retirada na loja'), ('delivery', 'Entrega')], default='pickup', max_length=20, verbose_name='tipo de entrega')),
                ('customer_name', models.CharField(max_length=200, verbose_name='nome do cliente')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='e-mail do cliente')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='telefone do cliente')),
                ('delivery_address', models.TextField(blank=True, verbose_name='endereço de entrega')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='data/hora agendada')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='subtotal')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='frete')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=200, verbose_name='nome do produto')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='subtotal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='pedido')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
            },
        ),
    ]
